import { WebsiteGenerationOptions } from '@/lib/types';

export function createWebsiteGenerationSystemPrompt(): string {
  return `You are an expert web developer and designer who creates stunning personal websites. 
You excel at:
- Converting markdown to semantic HTML
- Writing modern, maintainable CSS
- Creating responsive layouts
- Implementing beautiful animations
- Ensuring accessibility
- Tailoring content presentation for specific audiences

You MUST respond with valid JSON containing the generated HTML in the 'html' field.`;
}

export function createWebsiteGenerationPrompt({
  markdownContent,
  style = 'modern',
  colorScheme = 'auto',
  visitorContext
}: WebsiteGenerationOptions): string {
  return `
    Create a stunning personal website using this markdown content, specifically tailored for a ${visitorContext.type} 
    in the ${visitorContext.industry} industry${visitorContext.companyName ? ` from ${visitorContext.companyName}` : ''}.
    
    Visitor's Interests: ${visitorContext.interests.join(', ')}
    ${visitorContext.specificInterests ? `\nSpecific Interests: ${visitorContext.specificInterests}` : ''}

    Content Structure:
    1. A hero section with the name and a brief intro, emphasizing aspects relevant to the visitor's interests
    2. A clean, organized layout highlighting the most relevant experience and skills for this visitor
    3. Projects and achievements that align with the visitor's industry and interests
    4. Customized sections that demonstrate value specific to the visitor's context
    5. Contact information and relevant calls to action

    Design Requirements:
    1. Style: ${style} design with these specific features:
       - Modern typography with system fonts (no external fonts)
       - Proper spacing and hierarchy
       - Smooth transitions and hover effects
       - ${style === 'modern' ? 'Subtle gradients and shadows' : 
          style === 'minimal' ? 'Clean lines and minimal decoration' :
          style === 'bold' ? 'Strong colors and impactful typography' :
          'Creative layouts and unique visual elements'}

    2. Color Scheme: ${colorScheme} mode with:
       - A cohesive color palette
       - Proper contrast for accessibility
       - ${colorScheme === 'auto' ? 'CSS variables for color theming and a theme toggle button' : 'Optimized colors for ' + colorScheme + ' mode'}
       - Subtle accents for interactive elements

    3. Technical Requirements:
       - Fully responsive design using CSS Grid and Flexbox
       - CSS variables for consistent theming
       - Semantic HTML5 elements
       - Proper meta tags for SEO
       - No external resources or scripts
       - Inline CSS only
       - Proper ARIA labels and roles for accessibility

    4. Interactive Elements:
       - Smooth hover states on interactive elements
       - Subtle animations for section transitions
       - If auto color scheme, include a theme toggle with animation

    5. AI Notice:
       - Include a subtle but clear notice that this page was generated by AI
       - Emphasize that while the presentation is automated, all content is authentic

    Here's the markdown content to convert:
    ${markdownContent}

    Return the complete HTML code with inline styles in the 'html' field of a JSON response. The HTML should be a complete, valid document with proper head and body sections.
  `;
} 